language: ruby

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

rvm:
  - 2.3.4
  - 2.4.2

bundler_args: --jobs=3 --retry=3

cache: bundler

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
